apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: locust
  name: locust
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/locust
spec:
  replicas: 1
  selector:
    matchLabels:
      run: locust
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: locust
    spec:
      containers:
      - env:
        - name: LOCUST_MODE
          value: master
        - name: INSECURE_SSL
          value: "true"
        - name: TARGET_URL
          value: https://docker.p4.greenpeace.org
        image: gcr.io/planet-4-151612/locust:0.0.1
        imagePullPolicy: Always
        name: locust
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
