#!/usr/bin/env bash
set -e

LOCUST_CMD="/usr/local/bin/locust"

LOCUST_OPTS="-f ${SCENARIO_FILE} --host=${TARGET_URL}"

if [ "${LOCUST_MODE}" = "master" ]
then
  LOCUST_OPTS="${LOCUST_OPTS} --master"
elif [[ "${LOCUST_MODE}" = "slave" ]]
then
  LOCUST_OPTS="${LOCUST_OPTS} --slave --master-host=${MASTER_HOST}"
fi

echo "=> Starting locust $(${LOCUST_CMD} -v)"
echo "$LOCUST_CMD $LOCUST_OPTS"

exec "${LOCUST_CMD}" "${LOCUST_OPTS}"
