apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: locust-dev-slave
    p4.greenpeace.org/locust: dev.p4.greenpeace.org
  name: locust-dev-slave
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/locust-dev-slave
spec:
  replicas: 5
  selector:
    matchLabels:
      run: locust-dev-slave
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: locust-dev-slave
        p4.greenpeace.org/locust: dev.p4.greenpeace.org
    spec:
      containers:
      - env:
        - name: LOCUST_MODE
          value: slave
        - name: INSECURE_SSL
          value: "true"
        - name: LOCUST_MASTER
          value: locust-dev-master
        - name: TARGET_URL
          value: https://dev.p4.greenpeace.org
        image: gcr.io/planet-4-151612/locust:0.0.1
        imagePullPolicy: IfNotPresent
        name: locust-dev-slave
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: locust-dev-autoscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: locust-dev-slave
  minReplicas: 5
  maxReplicas: 30
  targetCPUUtilizationPercentage: 60
